name: Run PointlessWatcher

on:
  schedule:
    - cron: "0 0,12 * * *"  # 日本時間9:00と21:00に実行
  workflow_dispatch:        # 手動実行も可能

jobs:
  run-watcher:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Node.js をセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: watcher.js を実行
        run: node watcher.js
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
